env: "development"
cadence:
  domain: "test-domain"
  service: "cadence-frontend"
  hostPort: "host.docker.internal:7933"
  serverBaseURL: "http://localhost:8080"
  workflows:
    waitingwf: "WaitingWorkflow"

